INSERT INTO authors (first_name, last_name) VALUES
('Jane', 'Austen'),
('Mark', 'Twain'),
('George', 'Orwell'),
('J.R.R.', 'Tolkien'),
('F. Scott', 'Fitzgerald'),
('Ernest', 'Hemingway'),
('Charles', 'Dickens'),
('Agatha', 'Christie'),
('Leo', 'Tolstoy'),
('H.G.', 'Wells'),
('J.K.', 'Rowling'),
('Isaac', 'Asimov'),
('Arthur', 'Conan Doyle'),
('J.D.', 'Salinger'),
('Stephen', 'King'),
('Harper', 'Lee'),
('Gabriel', 'García Márquez'),
('Virginia', 'Woolf'),
('James', 'Joyce'),
('Aldous', 'Huxley'),
('Ray', 'Bradbury'),
('William', 'Shakespeare'),
('Jules', 'Verne'),
('Mary', 'Shelley'),
('Herman', 'Melville');
